### ISSUE TITLE
Change license to match libpg_query

### ISSUE THREAD

**Issue by lfittl** [tdbgamer/libpg_query-sys#1]
Hi @tdbgamer - thanks for creating these FFI bindings!

I was curious if you would be open to change the license to a BSD-type license, like pg_query has it (https://github.com/lfittl/libpg_query/blob/10-latest/LICENSE).

Whilst the Mozilla Public License is generally a great license, it has a few more restrictions that can make it complicated to use in certain situations, and it would be helpful if projects using the "pg_query" name match the license of the main project.

**Comment by autarch** [comment]
This is done in 0.1.3.
