### ISSUE TITLE
Update libpg_query to avoid build failure on glibc >= 2.38

### ISSUE THREAD

**Issue by jbg** [tdbgamer/libpg_query-sys#7]
The vendored libpg_query fails to build on glibc >= 2.38 due to [a symbol collision](https://github.com/pganalyze/libpg_query/pull/203); versions 15-4.2.3 and later of libpg_query have the fix. (15-4.2.4 is the current version for pg 15, 16-5.0.0 is also out.)

**Comment by autarch** [comment]
I tried to update but both 15-x and 16-x fail to compile for me. I'm not really using this crate myself these days. If you're using it would you be up for investigating?

**Comment by autarch** [comment]
Hmm, I just tried this again and it worked fine. I think I just had to delete `target` after switching the `libpg_query` tag.

**Comment by autarch** [comment]
This is done in v0.4.0.
